// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests psychologists based on user needs.
 *
 * - suggestPsychologists - A function that handles the psychologist suggestion process.
 * - SuggestPsychologistsInput - The input type for the suggestPsychologists function.
 * - SuggestPsychologistsOutput - The return type for the suggestPsychologists function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPsychologistsInputSchema = z.object({
  issues: z
    .array(z.string())
    .describe('An array of issues or topics the user wants help with.'),
});
export type SuggestPsychologistsInput = z.infer<typeof SuggestPsychologistsInputSchema>;

const SuggestPsychologistsOutputSchema = z.object({
  psychologistSuggestions: z
    .array(z.string())
    .describe('An array of psychologist names that are suggested for the user.'),
});
export type SuggestPsychologistsOutput = z.infer<typeof SuggestPsychologistsOutputSchema>;

export async function suggestPsychologists(input: SuggestPsychologistsInput): Promise<SuggestPsychologistsOutput> {
  return suggestPsychologistsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPsychologistsPrompt',
  input: {schema: SuggestPsychologistsInputSchema},
  output: {schema: SuggestPsychologistsOutputSchema},
  prompt: `You are an expert system for a mental health app. Based on the issues a user is facing, suggest psychologists who specialize in those areas.

Issues: {{issues}}

Psychologist Suggestions:`,
});

const suggestPsychologistsFlow = ai.defineFlow(
  {
    name: 'suggestPsychologistsFlow',
    inputSchema: SuggestPsychologistsInputSchema,
    outputSchema: SuggestPsychologistsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
