// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests tutors based on the courses the student is taking.
 *
 * - suggestTutors - A function that handles the tutor suggestion process.
 * - SuggestTutorsInput - The input type for the suggestTutors function.
 * - SuggestTutorsOutput - The return type for the suggestTutors function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTutorsInputSchema = z.object({
  courses: z
    .array(z.string())
    .describe('An array of course names that the student is taking.'),
});
export type SuggestTutorsInput = z.infer<typeof SuggestTutorsInputSchema>;

const SuggestTutorsOutputSchema = z.object({
  tutorSuggestions: z
    .array(z.string())
    .describe('An array of tutor names that are suggested for the courses.'),
});
export type SuggestTutorsOutput = z.infer<typeof SuggestTutorsOutputSchema>;

export async function suggestTutors(input: SuggestTutorsInput): Promise<SuggestTutorsOutput> {
  return suggestTutorsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTutorsPrompt',
  input: {schema: SuggestTutorsInputSchema},
  output: {schema: SuggestTutorsOutputSchema},
  prompt: `You are a tutor suggestion expert for university students. Based on the courses that the student is taking, suggest tutors that other students with a similar academic profile have used in the past.

Courses: {{courses}}

Tutor Suggestions:`,
});

const suggestTutorsFlow = ai.defineFlow(
  {
    name: 'suggestTutorsFlow',
    inputSchema: SuggestTutorsInputSchema,
    outputSchema: SuggestTutorsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
