import type { Tutor, Course } from './types';

export const courses: Omit<Course, 'id'>[] = [
  // Ingeniería Civil en Informática y Telecomunicaciones
  { name: 'Álgebra y Geometría' },
  { name: 'Cálculo I' },
  { name: 'Programación' },
  { name: 'Química' },
  { name: 'Comunicación para la Ingeniería' },
  { name: 'Álgebra Lineal' },
  { name: 'Cálculo II' },
  { name: 'Mecánica' },
  { name: 'Programación Avanzada' },
  { name: 'Ecuaciones Diferenciales' },
  { name: 'Cálculo III' },
  { name: 'Calor y Ondas' },
  { name: 'Estructura de Datos y Algoritmos' },
  { name: 'Probabilidades y Estadísticas' },
  { name: 'Electricidad y Magnetismo' },
  { name: 'Electrónica y Electrotecnia' },
  { name: 'Bases de Datos' },
  { name: 'Desarrollo Web y Móvil' },
  { name: 'Optimización' },
  { name: 'Señales y Sistemas' },
  { name: 'Arquitectura y Organización de Computadores' },
  { name: 'Bases de Datos Avanzadas' },
  { name: 'Redes de Datos' },
  { name: 'Sistemas Operativos' },
  { name: 'Ingeniería de Software' },
  { name: 'Contabilidad y Costos' },
  { name: 'Gestión Organizacional' },
  { name: 'Taller de Redes y Servicios' },
  { name: 'Comunicaciones Digitales' },
  { name: 'Inteligencia Artificial' },
  { name: 'Introducción a la Economía' },
  { name: 'Sistemas Distribuidos' },
  { name: 'Criptografía y Seguridad en Redes' },
  { name: 'Arquitectura de Software' },
  { name: 'Data Science' },
  { name: 'Evaluación de Proyectos TIC' },
  { name: 'Tecnologías Inalámbricas' },
  { name: 'Proyectos en TICs I' },
  { name: 'Arquitecturas Emergentes' },
  { name: 'Proyectos en TICs II' },

  // Ingeniería Civil Industrial
  { name: 'Termodinámica' },
  { name: 'Microeconomía' },
  { name: 'Inferencia Estadística' },
  { name: 'Mecánica de Fluidos' },
  { name: 'Macroeconomía' },
  { name: 'Investigación de Operaciones' },
  { name: 'Finanzas' },
  { name: 'Liderazgo y Emprendimiento' },
  { name: 'Simulación' },
  { name: 'Gestión de Operaciones' },
  { name: 'Ingeniería Económica' },
  { name: 'Marketing' },
  { name: 'Logística' },
  { name: 'Gestión de Calidad y Procesos' },
  { name: 'Gestión Estratégica' },
  { name: 'Evaluación de Proyectos' },
  { name: 'Taller de Ingeniería Industrial' },
  
  // Ingeniería Civil en Obras Civiles
  { name: 'Ingeniería de Materiales' },
  { name: 'Estática' },
  { name: 'Mecánica de Sólidos' },
  { name: 'Topografía' },
  { name: 'Edificación' },
  { name: 'Análisis Estructural' },
  { name: 'Mecánica de Suelos' },
  { name: 'Tecnología del Hormigón' },
  { name: 'Hidrología' },
  { name: 'Diseño Estructural' },
  { name: 'Ingeniería de Costos' },
  { name: 'BIM (Building Information Modeling)' },
  { name: 'Hidráulica' },
  { name: 'Diseño en Hormigón' },
  { name: 'Ingeniería de Fundaciones' },
  { name: 'Ingeniería Ambiental' },
  { name: 'Diseño en Acero' },
  { name: 'Hidráulica Urbana' },
  { name: 'Planificación de Proyectos' },
  { name: 'Diseño de Caminos' },
  { name: 'Taller de Proyectos' },
  { name: 'Ingeniería Sísmica' },
  
  // Cursos de Formación General y Electivos
  { name: 'Curso de Formación General' },
  { name: 'Inglés General I' },
  { name: 'Inglés General II' },
  { name: 'Inglés General III' },
  { name: 'Práctica Profesional I' },
  { name: 'Práctica Profesional II' },
  { name: 'Electivo Profesional' },
  { name: 'Actividad de Titulación' },
];

export const tutors: Omit<Tutor, 'id'>[] = [
  {
    name: 'Ana García',
    imageUrl: 'https://placehold.co/200x200.png',
    rating: 4.9,
    reviews: 120,
    hourlyRate: 15000,
    courses: ['Programación', 'Cálculo II'],
    bio: 'Desarrolladora full-stack con experiencia y pasión por la enseñanza. Me especializo en desglosar conceptos de programación complejos en lecciones fáciles de entender. Mi objetivo es ayudarte no solo a aprobar, sino a sobresalir.'
  },
  {
    name: 'Carlos Rodríguez',
    imageUrl: 'https://placehold.co/200x200.png',
    rating: 4.8,
    reviews: 95,
    hourlyRate: 18000,
    courses: ['Mecánica', 'Cálculo II'],
    bio: 'Ingeniero mecánico con amor por la física. Creo en los ejemplos prácticos y la resolución de problemas para construir una base sólida en física y matemáticas avanzadas.'
  },
  {
    name: 'Sofía Martínez',
    imageUrl: 'https://placehold.co/200x200.png',
    rating: 5.0,
    reviews: 200,
    hourlyRate: 17000,
    courses: ['Química', 'Cálculo I'],
    bio: 'Doctora en Química. Disfruto ayudando a los estudiantes a navegar los desafíos de la química y a comprender los principios que dan forma a nuestro mundo.'
  },
  {
    name: 'Javier Hernández',
    imageUrl: 'https://placehold.co/200x200.png',
    rating: 4.7,
    reviews: 75,
    hourlyRate: 14000,
    courses: ['Álgebra y Geometría', 'Álgebra Lineal'],
    bio: 'Un graduado con un gran interés en el álgebra. Ofrezco explicaciones claras y concisas y aplicaciones del mundo real para que el aprendizaje sea atractivo y eficaz.'
  },
  {
    name: 'Tutor de Prueba',
    imageUrl: 'https://placehold.co/200x200.png',
    rating: 4.5,
    reviews: 50,
    hourlyRate: 10000,
    courses: ['Programación', 'Mecánica'],
    bio: 'Este es un tutor de prueba para fines de desarrollo y demostración.'
  }
];
